language: c

jobs:
  include:
    - os: linux
      arch: amd64
      dist: xenial
      compiler: gcc
    - os: linux
      arch: amd64
      dist: xenial
      compiler: clang
    - os: linux
      arch: arm64
      dist: xenial
      compiler: gcc
    - os: linux
      arch: arm64
      dist: xenial
      compiler: clang

script:
  - ./autotest-linux.sh